config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :hellos
  root 'hellos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hello.rb
class Hello < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  before_action :set_hello, only: [:show, :edit, :update, :destroy]

  # GET /hellos
  # GET /hellos.json
  def index
    @hellos = Hello.all
  end

  # GET /hellos/1
  # GET /hellos/1.json
  def show
  end

  # GET /hellos/new
  def new
    @hello = Hello.new
  end

  # GET /hellos/1/edit
  def edit
  end

  # POST /hellos
  # POST /hellos.json
  def create
    @hello = Hello.new(hello_params)

    respond_to do |format|
      if @hello.save
        format.html { redirect_to @hello, notice: 'Hello was successfully created.' }
        format.json { render :show, status: :created, location: @hello }
      else
        format.html { render :new }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hellos/1
  # PATCH/PUT /hellos/1.json
  def update
    respond_to do |format|
      if @hello.update(hello_params)
        format.html { redirect_to @hello, notice: 'Hello was successfully updated.' }
        format.json { render :show, status: :ok, location: @hello }
      else
        format.html { render :edit }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hellos/1
  # DELETE /hellos/1.json
  def destroy
    @hello.destroy
    respond_to do |format|
      format.html { redirect_to hellos_url, notice: 'Hello was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hello
      @hello = Hello.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hello_params
      params.require(:hello).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/views/hellos/_form.html.erb
<%= form_for(hello) do |f| %>
  <% if hello.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hello.errors.count, "error") %> prohibited this hello from being saved:</h2>

      <ul>
      <% hello.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hellos/edit.html.erb
<h1>Editing Hello</h1>

<%= render 'form', hello: @hello %>

<%= link_to 'Show', @hello %> |
<%= link_to 'Back', hellos_path %>

app/views/hellos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hellos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hellos.each do |hello| %>
      <tr>
        <td><%= hello.name %></td>
        <td><%= hello.email %></td>
        <td><%= link_to 'Show', hello %></td>
        <td><%= link_to 'Edit', edit_hello_path(hello) %></td>
        <td><%= link_to 'Destroy', hello, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hello', new_hello_path %>

app/views/hellos/new.html.erb
<h1>New Hello</h1>

<%= render 'form', hello: @hello %>

<%= link_to 'Back', hellos_path %>

app/views/hellos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hello.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @hello.email %>
</p>

<%= link_to 'Edit', edit_hello_path(@hello) %> |
<%= link_to 'Back', hellos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <%= csrf_meta_tags %>
    
    <div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>